
BATCH_SIZE: 32
IM_SIZE: 224
LEARNING_RATE: 0.001
N_EPOCHS: 10
DROPOUT_RATE: 0.0
REGULARIZATION_RATE: 0.0
N_FILTERS: 6
KERNEL_SIZE: 3
N_STRIDES: 1
POOL_SIZE: 2
N_DENSE_1: 1024
N_DENSE_2: 128
NUM_CLASSES: 4
PATCH_SIZE: 16
PROJ_DIM: 768
CLASS_NAMES: ["Fibres", "Nanowires", "Particles","Powder"]
